### ISSUE TITLE
关于图片的编号1.1能否修改为1-1

### ISSUE THREAD

**Issue by Aglargil** [disc0ver-csu/csu-latex-template#26]
图片的编号1.1能否修改为1-1

**Comment by sikouhjw** [comment]
https://github.com/disc0ver-csu/csu-thesis/blob/41f721215f7f0f58a74d083fc37f95a1b164c951/undergraduate.cls#L477

**Comment by Aglargil** [comment]
请问这一行要修改成什么呢，我还是没实现1-1的效果

**Comment by sikouhjw** [comment]
是模板的设计有问题。
https://github.com/disc0ver-csu/csu-thesis/blob/41f721215f7f0f58a74d083fc37f95a1b164c951/csuthesis_main.tex#L21-L22
的作用是让 `chapter` 作为图标标题的上级计数器，而这重置了
https://github.com/disc0ver-csu/csu-thesis/blob/41f721215f7f0f58a74d083fc37f95a1b164c951/undergraduate.cls#L477
的效果。

所以将
```tex
\renewcommand{\thefigure}{\arabic{section}-\arabic{figure}}
```
写在
https://github.com/disc0ver-csu/csu-thesis/blob/41f721215f7f0f58a74d083fc37f95a1b164c951/csuthesis_main.tex#L21-L22
后面就可以了。

**Comment by Aglargil** [comment]
好的，谢谢您的帮助，这份模版给我的毕业设计带来了很大的帮助，十分感谢！
