### ISSUE TITLE
最后一次求助了！关于封面字体

### ISSUE THREAD

**Issue by Aglargil** [disc0ver-csu/csu-latex-template#28]
封面内容要求小二号楷体GB2312，现在字体大小是三号，请问应该怎么修改呢

**Comment by Edwardzcn** [comment]
https://github.com/disc0ver-csu/csu-thesis/blob/9cf814999d99cc868a857b3bada65be3c74a26ba/undergraduate.cls#L206

Hi，模板设计封面内容字体是小二号，你可以从这一行代码看到。这个对封面栏目和内容都是生效的。

**Comment by Aglargil** [comment]
谢谢
