### ISSUE TITLE
请问目录的第n章的字体能否调成不加粗的呢

### ISSUE THREAD

**Issue by Aglargil** [disc0ver-csu/csu-latex-template#29]
如题

**Comment by sikouhjw** [comment]
你为什么不给代码？
https://github.com/disc0ver-csu/csu-thesis/blob/41f721215f7f0f58a74d083fc37f95a1b164c951/graduate.cls#L312-L313
问题不存在

**Comment by Edwardzcn** [comment]
你是不是用的overleaf或者老版本，v1.0.1这些问题都修了。

**Comment by Edwardzcn** [comment]
> 你为什么不给代码？
> 
> https://github.com/disc0ver-csu/csu-thesis/blob/41f721215f7f0f58a74d083fc37f95a1b164c951/graduate.cls#L312-L313
> 
> 
> 问题不存在

这个是graduate.cls这个暂时不用的，学士论文引入的是undergraduate.cls。
