### ISSUE TITLE
bug: 图表编号相关问题

### ISSUE THREAD

**Issue by sheli00** [disc0ver-csu/csu-latex-template#33]
#### 请确认

- [ √] 是当前最新的 [Release 版本](https://github.com/disc0ver-csu/csu-thesis/releases)
- [ √] 在项目 [README 指南](https://github.com/disc0ver-csu/csu-thesis/blob/master/README.md) 中没有找到解决办法

#### 问题描述

使用overleaf进行图片插入时，图片的序号错乱了，如何更改
如果我想要自定义图片的序号，该如何操作

#### 截图

![This is an image](https://pic.dogimg.com/2022/04/19/625e7415bfd4f.png)
![This is an image](https://pic.dogimg.com/2022/04/19/625e7417696da.png)

![This is an image](https://pic.dogimg.com/2022/04/19/625e7417ef9cf.png)
![This is an image](https://pic.dogimg.com/2022/04/19/625e741722d81.png)
**本地环境 (请补充下面信息):**

- OS: [e.g. Windows 11]
- TeX 发行版: [e.g. TeXLive2021, MiKTeX2019]
- TeX 编辑器: [e.g. overleaf]

**Comment by Edwardzcn** [comment]
这个可能是个bug，我刚刚跟之前修改图表样式的同学确认了下，参见提交 f9b295ade43621661dabfbbe58dc935a0406aed0 。

修改有bug，目前正在确定正确样式，可以先说下导言区修改样式的位置：

https://github.com/disc0ver-csu/csu-thesis/blob/1aec2b0beb3d728c17a6226162724b9e029f0a22/csuthesis_main.tex#L24-L28

我们之前理解学校word版本标准是按节编号，所以设定如上，我们会尽快修改，我们提供给您两种自行修改的方法。

如果你希望全局编号（即不携带章编号），建议你修改为：

```latex
\renewcommand{\theequation}{\arabic{equation}}
\renewcommand\thefigure{\arabic{figure}}
\renewcommand\thetable{\arabic{table}}
```

如果希望是逐章编号，则建议你修改为：

```latex
\renewcommand\theequation{\arabic{chapter}-\arabic{equation}}
\renewcommand\thefigure{\arabic{chapter}-\arabic{figure}}
\renewcommand\thetable{\arabic{chapter}-\arabic{table}}
```

可能还存在计数器不清零的情况，你需要在每章开始位置输入`\setcounter{figure}{0}` ，table和equation计数器同样。

**Comment by sheli00** [comment]
感谢，我希望按chapter编号

> \renewcommand\theequation{\arabic{chapter}-\arabic{equation}}
\renewcommand\thefigure{\arabic{chapter}-\arabic{figure}}
\renewcommand\thetable{\arabic{chapter}-\arabic{table}}

在图之前加上这个命令可以实现
![This is an image](https://pic.dogimg.com/2022/04/20/625fab14bb6de.png)
![This is an image](https://pic.dogimg.com/2022/04/20/625fab175a8d2.png)
