### ISSUE TITLE
摘要“关键词”三个字未加黑

### ISSUE THREAD

**Issue by abcvav** [disc0ver-csu/csu-latex-template#35]
#### 请确认

- [x] 是当前最新的 CSUThesis [Release 版本](https://github.com/disc0ver-csu/csu-thesis/releases)
- [x] 本地已安装好 TeXLive 或其他 TeX 发行版
- [x] 重新安装 TeXLive 和本模板后，问题仍然存在

#### Bug 描述

中文摘要处，“关键词”部分未加黑。

#### 复现步骤
直接编译就能看到，overleaf或本地编译都是这样

#### 截图
![image](https://user-images.githubusercontent.com/47599849/168514929-52093b85-3022-4d60-a2cd-0c9a04d1b105.png)

但是在`undergraduate.cls`文件中第`358`行处，已经使用加黑命令了，不过还是没有加黑。
![image](https://user-images.githubusercontent.com/47599849/168515112-a4c8525a-8a52-42d5-a5af-a54e075a6cfe.png)

**Comment by Edwardzcn** [comment]
是由于适配Overleaf，调整字体设置重定向加粗和斜体效果导致的。修改的方法如下，在`undergraduate.cls`文件中找到CJK字体族环境的设置，大概是117行，把里面参数改为`AutoFakeBold={3.17}`，启动AutoFakeBold，这样关键字和正文环境中\bfseries就可以正常使用了。

https://github.com/disc0ver-csu/csu-thesis/blob/893088bba9aa91bb65df682bf6561085919b7527/undergraduate.cls#L117-L119
