### ISSUE TITLE
关于正文的标点符号

### ISSUE THREAD

**Issue by smw1996** [disc0ver-csu/csu-latex-template#37]
在模板正文中，标点符号不对，而摘要里的中文标点符号是对的，请问在哪里修改呢？

#### 截图

**本地环境 (请补充下面信息):**

- OS: [e.g. Windows 10]
- TeX 发行版: [e.g. TeXLive2020, MiKTeX20
![d20d6fdebaef50f1cc52f7f8ae151a9](https://user-images.githubusercontent.com/46362562/171149114-69379a3a-29a1-4f78-9019-6cb34f6b501c.png)
19]
- TeX 编辑器: [e.g. TeXStudio, Visual Studio Code]
![4c7f650ba4d46db04d7b1fcfb5a91ee](https://user-images.githubusercontent.com/46362562/171149154-47ffdc0a-95cf-4333-a1ee-fc8c764cf217.png)

**Comment by Edwardzcn** [comment]
我本地没有出现类似情况，
![image](https://user-images.githubusercontent.com/32711483/172546627-445db0ee-f1e9-405b-a319-c84416427e75.png)
这里就是正文部分。而你给出的另一种comma的字体实际上是英文字体，比如下图中：
![image](https://user-images.githubusercontent.com/32711483/172547255-3dcf1f28-fafe-4ffb-97b8-53ef35e65d43.png)

实际上所以请你再确定是否是键入的是“，”还是','。
