### ISSUE TITLE
参考文献标号右对齐问题

### ISSUE THREAD

**Issue by abcvav** [disc0ver-csu/csu-latex-template#38]
#### 请确认

- [x] 是当前最新的 CSUThesis [Release 版本](https://github.com/disc0ver-csu/csu-thesis/releases)
- [x] 本地已安装好 TeXLive 或其他 TeX 发行版
- [x] 重新安装 TeXLive 和本模板后，问题仍然存在

#### Bug 描述

学校要求参考文献标号应该是左对齐的，然而模板是右对齐的，如图所示：

![image](https://user-images.githubusercontent.com/47599849/172177940-fe33192a-6794-45a9-8298-ebdc45a552cd.png)

[9]和[10]应该是左括号对齐，但是模板是右括号对齐的。

**Comment by abcvav** [comment]
找到解决办法了，见[这个网址](https://tex.stackexchange.com/questions/573544/aligning-biblatex-items-left)

**Comment by Edwardzcn** [comment]
OK, thx。下个版本会fix

**Comment by abcvav** [comment]
不过还是会有问题，这种方法[9]和[10]左对齐过后，[9]到参考文献条目的间距会比[10]大很多，但是学校要求间距相等
![image](https://user-images.githubusercontent.com/47599849/172287813-f82dc5e4-a53b-4aac-bf6e-d0b00f07dc61.png)

**Comment by Edwardzcn** [comment]
我看了一下本科生毕业论文模板，没有文字要求，但是图示确实是左对齐，间距相等。
![1654571845387](https://user-images.githubusercontent.com/32711483/172288307-e93cd425-fe49-47f7-8c48-4ce95d5d3ccb.png)

不过文献格式部分同研究生论文模板要求以及其他学校的要求相似，都是使用的GB7714-2015样式，数字标号样式是该[宏包](https://github.com/zepinglee/gbt7714-bibtex-style) 提供的，说实话我觉得这个更正式，但本科生毕业论文模板没有说要求该样式。

**Comment by abcvav** [comment]
其实是要求了的，，，如图所示，编号到文献条目的垂直间距要求是一个空格
![image](https://user-images.githubusercontent.com/47599849/172292103-0d40b02a-944a-4683-807f-88d27eceaef4.png)

**Comment by Edwardzcn** [comment]
> 其实是要求了的，，，如图所示，编号到文献条目的垂直间距要求是一个空格
> ![image](https://user-images.githubusercontent.com/47599849/172292103-0d40b02a-944a-4683-807f-88d27eceaef4.png)

我记到你的意思，我是说没要求GB7714-2015。

**Comment by abcvav** [comment]
哦哦😂

**Comment by hushidong** [comment]
加上选项：gbalign=gb7714-2015即可

**Comment by hushidong** [comment]
加上选项：gbalign=gb7714-2015即可

**Comment by Edwardzcn** [comment]
![image](https://user-images.githubusercontent.com/32711483/172550549-1d248c06-e215-47ee-a41b-575510649874.png)
dev版本已修复
