### ISSUE TITLE
已知bug：Windows环境下编译的目录页一级标题错位

### ISSUE THREAD

**Issue by Edwardzcn** [disc0ver-csu/csu-latex-template#4]
# 使用环境
- OS: Windows 10
- Tex发行版: Tex Live 2020
# 问题描述

Windows环境下编译可能会产生目录页一级标题错位如下图：
![W%ZA`~~YTN_A_DQ@D)T3HI3](https://user-images.githubusercontent.com/32711483/105965073-f591f180-60bd-11eb-8112-37682f0daf57.png)

日志报错为hbox溢出，不过在我本地和Overleaf上的测试版(Linux环境)，都没有出现类似问题，bug还在定位，不影响使用，后续应该会修复。

![UUZ6J011ZO}OM`B_V1AX51F](https://user-images.githubusercontent.com/32711483/105965321-37bb3300-60be-11eb-9077-36d4d6ccf7bb.png)
![}XN(3O32{2NFHJ_%I(V3I76](https://user-images.githubusercontent.com/32711483/105965327-38ec6000-60be-11eb-8df0-03ad10330315.png)

**Comment by loctempt** [comment]
![图片](https://user-images.githubusercontent.com/8164006/105966952-3ee34080-60c0-11eb-9b4e-1a4a8ea654dd.png)
我在windows环境编译没问题，看来还得继续排查
OS：Windows10
发行版：MiKTeX 21.1-x64

**Comment by Edwardzcn** [comment]
找到问题了，应该是出在ctex和其他控制目录样式的包兼容性问题上，详见 https://github.com/CTeX-org/ctex-kit/issues/472#issue-543423781以及https://github.com/stone-zeng/fduthesis/issues/73#issuecomment-491596140。

**Comment by Edwardzcn** [comment]
找到问题了，应该是出在ctex和其他控制目录样式的包兼容性问题上，详见 https://github.com/CTeX-org/ctex-kit/issues/472#issue-543423781  以及  https://github.com/stone-zeng/fduthesis/issues/73#issuecomment-491596140。

**Comment by Edwardzcn** [comment]
找到问题了，应该是出在ctex和其他控制目录样式的包兼容性问题上，详见 https://github.com/CTeX-org/ctex-kit/issues/472#issue-543423781以及https://github.com/stone-zeng/fduthesis/issues/73#issuecomment-491596140 。

**Comment by Edwardzcn** [comment]
找到问题了，应该是出在ctex和其他控制目录样式的包兼容性问题上，详见 https://github.com/CTeX-org/ctex-kit/issues/472#issue-543423781 以及 https://github.com/stone-zeng/fduthesis/issues/73#issuecomment-491596140 。

**Comment by Edwardzcn** [comment]
已经在v0.1.3dev版本中修复，同时添加了目录中一级标题后的省略号。
