### ISSUE TITLE
mac的Texpad无法编译

### ISSUE THREAD

**Issue by Joseph516** [disc0ver-csu/csu-latex-template#41]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/disc0ver-csu/csu-thesis/releases)
- [x] 在项目 [README 指南](https://github.com/disc0ver-csu/csu-thesis/blob/master/README.md) 中没有找到解决办法

#### 问题描述

mac的Texpad无法编译， 一直在转圈，无法生成pdf。

#### 截图

![image](https://user-images.githubusercontent.com/39769420/200561568-eae7964a-7813-4fbe-9caa-661b63fec809.png)

**本地环境 (请补充下面信息):**

- OS: MacOS
- TeX 发行版: MacTex 2022
- TeX 编辑器: TexPad 1.9.6

**Comment by sikouhjw** [comment]
报什么错？

**Comment by Joseph516** [comment]
Texpad没有报错，就是一直在转圈，无法输出。我用另外一个编辑器又试了一下，说是找不到字体，类似这种：Package fontspec Error: The font "SimSun" cannot be found.

**Comment by sikouhjw** [comment]
说明 mac 没有『中易宋体』，试试在
https://github.com/disc0ver-csu/csu-thesis/blob/a93d6879f1bb7989d3a179bda98897cb62fed444/csuthesis.cls#L220
加上 `fontset = mac`

**Comment by Edwardzcn** [comment]
为了匹配原始word模版，目前仍然使用几款商用字体，比如中易宋体`simsun.ttf`，中易黑体`simhei.ttf`。商业字体有版权所以没有在模版中上传。模版可以正常在Windows环境编译，MacOS 可以使用`fontset=none`更换字体集编写，但是还是对最终效果有影响。建议自己download解决，或者你可以用Overleaf（为了通过编译上传了font）。
